### ISSUE TITLE
NameError: name 'mode' is not defined

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/ceda-cc#12]
I was getting a name error from /home/badc/miniconda3/envs/ingest_py3/lib/python3.8/site-packages/ceda_cc/ceda_cc_config/utils_config.py

The mode in self.mode = mode below hadn't been assigned but it wasn't being used either so I commented that line out and the ceda-cc code ran ok.

We should correct the code in the github repo too.

`class NumericControl(object):
  """Check on a numeric object"""

  def __init__(self,tag,target_type=None,max_valid=None,min_valid=None,element_check=None, base_class=None):

    self.tag = tag

    self.mode = mode

    self.target_type = target_type

    self.base_class = base_class

    self.max_valid = max_valid

    self.min_valid = min_valid

    self.element_check = element_check`

**Comment by martinjuckes** [comment]
Error found on ingest4, ceda_cc on command line.

**Comment by martinjuckes** [comment]
Thanks .. fixed in master.
