### ISSUE TITLE
ceda-cc doesn't seem to be using the CCMI2022_CV.json

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/ceda-cc#13]
I ran ceda-cc from /software/datasets/ccmi on the ingest4 machine to check Olaf Morgenstern's data:
ceda-cc -p ccmi2022 -f /datacentre/arrivals/users/omorgenstern/ccmi-2022/v20210614/ztp_Amon_NIWA-UKCA2_refD1_r3i1p1f1_gn_196001-201812.nc

I found I got errors to do with incorrect institute_id (NIWA), source_id (NIWA-UKCA2) and ripf indices.
Yet NIWA and NIWA-UKCA2 are both listed in the [CCMI2022_CV.json](https://github.com/cedadev/ccmi-2022/blob/main/Tables/CCMI2022_CV.json) 

The full error report can be found in the following ccmi-2022 Github issue
https://github.com/cedadev/ccmi-2022/issues/17

**Comment by martinjuckes** [comment]
@charliepascoe : I don't think NIWA is in /home/badc/miniconda3/envs/ingest_py3/lib/python3.8/site-packages/ceda_cc/ceda_cc_config/config/ccmi2022/Tables/CCMI2022_CV.json .. if this file is out of date, can you update it?

**Comment by charliepascoe** [comment]
Yes I'll update it, I see now that NIWA was added about a month ago.
Still, it's weird that ceda-cc is complaining about the variant_id/ensemble_id.
