### ISSUE TITLE
NetCDF: HDF error aborts ceda-cc checks

### ISSUE THREAD

**Issue by mollymacrae** [cedadev/ceda-cc#30]
Two errors have come up with Meteo-France snapsi data that abort the ceda-cc checks when they are encountered:

- HDF error printed:
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
**OSError: [Errno -101] NetCDF: HDF error:** b'/datacentre/arrivals/users/dspecq/snapsi2/v20230215/free/s20191001/6hrPt/ta/ta_6hrPt_CNRM-CM61_free_s20191001-r4i1p1f1_gr_20191001-20191114.nc'

- Unknown file format error:
**OSError: [Errno -51] NetCDF: Unknown file format:** b'/datacentre/arrivals/users/dspecq/snapsi2/v20230215/free/s20191001/6hrPt/hus/hus_6hrPt_CNRM-CM61_free_s20191001-r42i1p1f1_gr_20191001-20191114.nc'

**Comment by agstephens** [comment]
Hi @mollymacrae: looks like this isn't a problem `ceda-cc`, more that the file isn't valid netcdf:

```
$ ncdump -h /datacentre/arrivals/users/dspecq/snapsi2/v20230215/free/s20191001/6hrPt/ta/ta_6hrPt_CNRM-CM61_free_s20191001-r4i1p1f1_gr_20191001-20191114.nc

ncdump: /datacentre/arrivals/users/dspecq/snapsi2/v20230215/free/s20191001/6hrPt/ta/ta_6hrPt_CNRM-CM61_free_s20191001-r4i1p1f1_gr_20191001-20191114.nc: 

/datacentre/arrivals/users/dspecq/snapsi2/v20230215/free/s20191001/6hrPt/ta/ta_6hrPt_CNRM-CM61_free_s20191001-r4i1p1f1_gr_20191001-20191114.nc: NetCDF: HDF error
```

**Comment by mollymacrae** [comment]
Hi Ag, 
Thank you for your reply, I'm running ceda-cc for a list of filepaths and currently it stops the check altogether when it encounters a bad file but I was wondering if the checks could abort for invalid files like this but keep running on the rest of the file list?

**Comment by mollymacrae** [comment]
Thank you!

Line I run:
$ ceda-cc -p snapsi -l filepaths.txt       
   
output:       
CV error: not all frequencies included in table_id list: ['6hrC']
CV error: not all table_ids included in frequency list: ['6hrRef']
ingestJson ...  /datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/ceda_cc_config/config/snapsi/Tables/ SNAPSI_6hr.json
ingestJson ...  /datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/ceda_cc_config/config/snapsi/Tables/ SNAPSI_6hrPt.json
ingestJson ...  /datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/ceda_cc_config/config/snapsi/Tables/ SNAPSI_6hrZ.json
ingestJson ...  /datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/ceda_cc_config/config/snapsi/Tables/ SNAPSI_6hrPtZ.json
ingestJson ...  /datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/ceda_cc_config/config/snapsi/Tables/ SNAPSI_6hrRef.json
1250 files, ['6hrPt', '6hrPtZ', '6hrZ']
**Traceback (most recent call last):
  File "/datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/bin/ceda-cc", line 8, in <module>
    sys.exit(main_entry())
  File "/datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/c4.py", line 34, in main_entry
    m.run(printInfo=True)
  File "/datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/c4_run.py", line 340, in run
    self.cc.checkFile( f, log=fLogger,attributeMappings=self.c4i.attributeMappings, getdrs=self.c4i.getdrs )
  File "/datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/c4_run.py", line 222, in checkFile
    self.ncReader.loadNc( fpath )
  File "/datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/file_utils.py", line 141, in loadNc
    self.loadNc__Netcdf4(fpath)
  File "/datacentre/processing3/snapsi/mmacrae/molly-s-new-venv/lib/python3.8/site-packages/ceda_cc/file_utils.py", line 259, in loadNc__Netcdf4
    self.nc = self.netCDF4.Dataset(fpath, 'r')
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/datacentre/arrivals/users/dspecq/snapsi2/v20230215/nudged/s20191001/6hrPt/ta/ta_6hrPt_CNRM-CM61_nudged_s20191001-r6i1p1f1_gr_20191001-20191114.nc'**

**Comment by martinjuckes** [comment]
Hi Molly, you need to run with the `--cae` flag (catch-all-errors -- see `ceda-cc -h`). The default exception handling is to catch the exception, print a message to the log file and then, if the exception is not recognised, raise a new exception. The `--cae` flag suppresses the last step.

**Comment by mollymacrae** [comment]
Thank you, this worked!
